### ISSUE TITLE
1337x and LimeTor not working only PirateBay working !!!

### ISSUE THREAD

**Issue by imalixch** [priyanktejani/fluid-torrent-search-engine#1]
Hi, the overall app is nice, but there are issues -> 1337x and LimeTor not working. Can you please check what's the problem?

**Comment by priyanktejani** [comment]
Lime Torrent is working fine for me. However, in 1337x the issue with the web scrapping. Use VPN for Lime Torrent.

**Comment by imalixch** [comment]
Hmm, well with VPN Lime Torrent still not working and please tell me how can I add more torrent websites. And how to contact you can you give me your email or Whatsapp. Thanks

**Comment by imalixch** [comment]
?

**Comment by priyanktejani** [comment]
email: tejanipriyank7@gmail.com
